README.md

From now on, the Readme mentions only ``chipsalliance/verible-linter-action@main`` action.

Fix action name in readme

---

.github/workflows/Test.yml
Dockerfile
action.yml
entrypoint.sh

Close #3
Unfortunately, when the image is built automatically as part of a Container Action, it seems that global environment variables are not inherited. Therefore, enabling BuildKit globally through DOCKER_BUILDKIT does not work. That would be desirable in order to use https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md#build-mounts-run---mount in the dockerfile. For now, I worked around it by using a COPY statement (a layer) instead. Nonetheless, I kept the commit isolated, because it might be reverted when building the image is decoupled from the execution.
I added a very simple CI workflow for testing the execution of the Action. Yet, since there is no "demo" project here, execution is rather useless. It would be interesting if someone familiar with …

Convert to Container Action

---

Dockerfile
action.py
action.yml
entrypoint.sh

This PR enables creating automatic change suggestions.
Enabled by default, can be disabled by setting `suggest_fixes` input to value other than `true`.
Additionall changes are:
* newer version of Verible
* changes suggested by shellcheck linter

Use autofix feature of Verible to suggest changes in PRs

---

.github/workflows/Container.yml
action.yml

This is a folloy-up of #4.
As commented in #3, building the container image separatedly and the using it at runtime can reduce the execution time for users of this Action. In this PR, a workflow is added, which builds image `ghcr.io/chipsalliance/verible-linter-action` and pushes it to the GitHub Container Registry, using the default token. Then, in the Action, that image is used instead of the `Dockerfile`.
- Current execution time (92s): https://github.com/chipsalliance/verible-linter-action/actions/runs/1192256099
- Image build and push time (131s): https://github.com/umarcor/verible-linter-action/actions/runs/1194493666
- Execution time using the image (22s): https://github.com/umarcor/verible-linter-action/actions/runs/1194493667
The workflows are scheduled weekly. Feel free to …

Push container image to GHCR and use it in the Action

---

Dockerfile
entrypoint.sh
rdf_gen.py

We can use `--autofix` option of Verible to provide change suggestions that can be easily applied on GitHub.
However, with `errorformat` which is currently used to pass information to Reviewdog, this is not possible.
Verible provides output in two formats:
* patch in unidiff
* log in errorformat (documented here: https://vim-jp.org/vimdoc-en/quickfix.html#error-file-format)
This PR adds a script which merges the information from these two files to provide a JSON-based Reviewdog Diagnostic Format file.
The RDFormat file is then used as input to Reviewdog, which posts code review with change suggestions.
Example results can be viewed here: https://github.com/antmicro/gha-playground/pull/47#discussion_r703638460
The feature of autofix can be disabled by setting the `suggest_fixes` input to …

Use Reviewdog Diagnostic Format to post reviews with change suggestions

---

entrypoint.sh

The action needs to handle two remotes. One for the main repo, and the other for the source of the PR.
This wasn't handled properly and is fixed here.
The problem appeared here:
https://github.com/lowRISC/ibex/pull/1434
Right now the script retrieves the URL of the remote from `event.json` and fetches the right branch from it.
Additionally, hash of the `HEAD` is printed so that it's easy to confirm correctness of operation.
I've checked these scenarios:
1. The branch used in a PR doesn't exist in the main repo, and it works.
2. The branch used in a PR does exist in the main repo, and it's actually fetched from the fork. (Previously the script tried to fetch it from mainline)

Fix remote url handling when a PR from a fork is created

---

action.py

The newer version of Verible: 
1. Prints rule violations to `stderr`, not `stdout` (This caused problems in Ibex repository).
2. Uses different values for autofix argument (I thought I had added this change already, and I'm adding it now).
A test PR was recreated here:
https://github.com/antmicro/gha-playground/pull/93

Fix missing output from action.py

---

action.py

Previously, the action would exit with non-zero code whenever rule violations were found, even if the violations did not belong to the changes in PR.
We could either change it to return non-zero when violations are relevant, or always return zero.
I'm changing this to always exit successfully and my reasoning here is that, if there are relevant violations, we'll see them in code review (so we don't really need the negative flag), and we can use non-zero exit codes for internal errors in the action, not related to output from Verible.

exit the action without error

---

action.yml
entrypoint.sh

This allows to choose whether the action should fail or not, depending on the result of running Verible.
Use `fail_on_error: 'true'` to fail the action if a rule violation that is relevant to a PR exists.
For testing purposes, this PRs have been created:
1. Failing disabled, errors were posted as code review, but the workflow was successful anyway:
https://github.com/antmicro/gha-playground/pull/95
2. Failing enabled, errors were posted as code review and the workflow failed:
https://github.com/antmicro/gha-playground/pull/96
3. Failing enabled, but no rule violations were found, thus the workflow succeeded:
https://github.com/antmicro/gha-playground/pull/97

Add action input fail_on_error

---

.github/workflows/Test.yml

The test would fail because the default reporter is "github-pr-review" and there wasn't a token provided.
The reason I change the test, and not the code of the action, is because I assume that the correct usage of the action is to either:
1. Use a reporter that requires the token ("github-pr-review") AND provide the token.
2. Use a reporter that doesn't require the token (for example "local").
The workflow was successful here: https://github.com/antmicro/verible-linter-action/actions/runs/1266083502

add GitHub token to test

---

Dockerfile

Re-opening of #19 due to an error on my end.
Similar to the [verible-formatter-action](https://github.com/chipsalliance/verible-formatter-action), fetch the most recent version of verible and perform the linting.

Always use latest verible

---

Dockerfile

Download script would only filter available downloads by target operating system, but not by architecture. Since Verible release [v0.0-2950-g1bb4ef62](https://github.com/chipsalliance/verible/releases/tag/v0.0-2950-g1bb4ef62) AArch64 builds became available, which were being downloaded despite the fact that container is being built for x86_64 platform.

Download Verible prebuild for x86_64 architecture

---

rdf_gen.py

Current versions of Verible puts column range in the log, which breaks assumption that the log only contains first column where given error appears. This fix strips the last column number, fixing integer parsing error.

rdf_gen: Use only start column number when parsing errorformat log

---

entrypoint.sh

Otherwise we see the following when running in a container:
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

Fix git error in container

---

README.md
trigger-receive/action.yml
trigger-send/action.yml

Hide all the details about artifacts and downloading from user. Users should not be required to copy the whole scripts to their workflows, let's keep then in a subaction in our repo so it's cleaner and easier to maintain.

Simplify triggers usage

---

action.yml

This pull request adds additional step in the action, which uploads full Verible linter log to artifacts.

Add linter log to artifacts

---

README.md

Double workflow setup makes it harder to notice problems with actual linting action, because it's not visible from pull request page. Changing workflow trigger to `pull_request_target` with different reference to be checked out allows for running linting process with elevated permissions for pull requests from forked repositories.
Required permissions are explicitly listed to limit access to unused GitHub API endpoints.

Replace double workflow setup with `pull_request_target` workflow trigger

---

README.md
action.py
action.yml
entrypoint.sh

Currently action will only check files with `.sv` and `.v` extensions. Additional input parameter is introduced, called `extensions`, which can be used for overriding checked extensions set. This allows for adding e.g. include files to linting input.

Allow for overriding file extensions to be checked by linter

---

action.yml

Version 3 is using Node v16 which is deprecated and may be removed in the future.
I'm unsure whether this change requires a major version bump to _this_ action. [upload-artifact@v4](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md) changes whether the same artifact can be uploaded multiple times and replace itself which I suppose has an observable effect.

Update upload-artifact action to v4

---

rdf_gen.py

when this condition is reached a plaintext line is printed to the log that reviewdog later parses. Reviewdog then spits out the error "reviewdog: parse error: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 1:1): invalid value Did"

Fix print issue causing reviewdog to break
